"review needed :eyes:":
  - src/**/*

"documentation :book:":
  - README.md

"tooling :wrench:":
  - .github/**/*
  - src/scripts/*
  - netlify.toml

"dependencies :package:":
  - package.json
  - yarn.lock

"internal :house:":
  - gatsby-browser.js
  - gatsby-config.js
  - gatsby-node.js
  - gatsby-ssr.js
  - .all-contributorsrc

"translation :earth_africa:":
  - src/content/translations/**/*
  - src/intl/*
  - src/utils/translations.js

"content :fountain_pen:":
  - src/pages/*
  - src/pages-conditional/*
  - src/content/**/*

"event :date:":
  - src/data/community-events.json
